name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          # Only use PR SHA for pull request events
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          # Enable PR mode only for pull request events
          pr-mode: ${{ github.event_name == 'pull_request' }}
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1973545248 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'